[icons]
# font awesome
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
# smile emoji
MyNiceProgram = "😛"

[aliases]
"telegramdesktop" = "Telegram"
"firefox" = "Firefox"
"org.kde.kcalc" = "KCalc"
"org.kde.dolphin" = "Dolphin"
"foot" = "Foot"
"org.qbittorrent.qBittorrent" = "QBittorrent"
"org.gnome.Nautilus" = "Nautilus"
"Brave-browser" = "Brave"
"pcmanfm" = "PCManFM"
"krita" = "Krita"

[general]
separator = " / "
